### ISSUE TITLE
Individual Post

### ISSUE THREAD

**Issue by gideaofranco** [zakirsajib/Author-Signature#2]
Hi Zakir,

When we open the detail of post, the signature is not showed.

I fix this bug in my local repository.

Can you make me a contributor of your project to send it?

Thanks,
Gideão Franco.

**Comment by zakirsajib** [comment]
Yes I will make you contributor but I am not in front of pc right now.  I will be at home later today. 
On 14 Aug 2015 19:00, Gideão Franco <notifications@github.com> wrote:Hi Zakir,

When we open the detail of post, the signature is not showed.

I fix this bug in my local repository.

Can you make me a contributor of your project to send it?

Thanks,
Gideão Franco.

**Comment by gideaofranco** [comment]
It's done!

The bug fix was committed! Please check if you liked! ;-)

Thanks,
Gideão Franco.
